# Pandas高级应用

## 12.1 分类数据

In [1]:
import numpy as np; import pandas as pd

In [2]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)

In [3]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [4]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [5]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [6]:
values = pd.Series([0, 1, 0, 0] * 2)

In [7]:
dim = pd.Series(['apple', 'orange'])

In [8]:
dim

0     apple
1    orange
dtype: object

In [9]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [10]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

### pandas的分类类型

In [11]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [13]:
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [15]:
N = len(fruits)

In [16]:
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': np.random.randint(3, 15, size=N),
                   'weight': np.random.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])

In [17]:
df

basket_id   fruit  count    weight
0          0   apple     14  3.273083
1          1  orange     10  2.304683
2          2   apple      6  2.548586
3          3   apple      7  0.345079
4          4   apple     13  1.213091
5          5  orange     13  0.358530
6          6   apple     11  3.514820
7          7   apple     10  3.548840

In [18]:
fruit_cat = df['fruit'].astype('category')

In [19]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [20]:
df

basket_id   fruit  count    weight
0          0   apple     14  3.273083
1          1  orange     10  2.304683
2          2   apple      6  2.548586
3          3   apple      7  0.345079
4          4   apple     13  1.213091
5          5  orange     13  0.358530
6          6   apple     11  3.514820
7          7   apple     10  3.548840

In [21]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: object

In [22]:
c = fruit_cat.values

In [23]:
c

[apple, orange, apple, apple, apple, orange, apple, apple]
Categories (2, object): [apple, orange]

In [24]:
type(c)

pandas.core.arrays.categorical.Categorical

In [25]:
df.values

array([[0, 'apple', 14, 3.2730834520487595],
       [1, 'orange', 10, 2.3046830987590283],
       [2, 'apple', 6, 2.5485859881104718],
       [3, 'apple', 7, 0.3450786630166025],
       [4, 'apple', 13, 1.2130912029239553],
       [5, 'orange', 13, 0.35853029974876716],
       [6, 'apple', 11, 3.514819807446578],
       [7, 'apple', 10, 3.548839923113044]], dtype=object)

In [26]:
type(df.values)

numpy.ndarray

In [27]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [28]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [29]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: object

In [30]:
df['fruit'] = df['fruit'].astype('category')

In [31]:
df.fruit

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [32]:
df.fruit

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [33]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [34]:
my_categories

[foo, bar, baz, foo, bar]
Categories (3, object): [bar, baz, foo]

In [35]:
categories = ['foo', 'bar', 'baz']

In [48]:
codes = [0, 1, 2, 2, 0, 0, 1]

In [50]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [43]:
categories

['foo', 'bar', 'baz']

In [51]:
codes

[0, 1, 2, 2, 0, 0, 1]

In [52]:
my_cats_2

[foo, bar, baz, baz, foo, foo, bar]
Categories (3, object): [foo, bar, baz]

In [53]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [54]:
ordered_cat

[foo, bar, baz, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

In [55]:
my_cats_2.as_ordered()

[foo, bar, baz, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

### 用分类进行计算

In [56]:
np.random.seed(12345)

In [57]:
draws = np.random.randn(1000)

In [58]:
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [59]:
bins = pd.qcut(draws, 4)

In [60]:
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [66]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [67]:
bins

[Q2, Q3, Q2, Q2, Q4, ..., Q3, Q2, Q1, Q3, Q4]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [68]:
bins.codes[:10]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3], dtype=int8)

In [69]:
bins = pd.Series(bins, name='quartile')

In [70]:
bins

0      Q2
1      Q3
2      Q2
3      Q2
4      Q4
5      Q4
6      Q3
7      Q3
8      Q4
9      Q4
10     Q4
11     Q1
12     Q3
13     Q3
14     Q4
15     Q4
16     Q1
17     Q2
18     Q4
19     Q2
20     Q2
21     Q3
22     Q4
23     Q1
24     Q2
25     Q3
26     Q3
27     Q3
28     Q3
29     Q4
       ..
970    Q2
971    Q1
972    Q2
973    Q4
974    Q3
975    Q1
976    Q1
977    Q2
978    Q2
979    Q3
980    Q3
981    Q1
982    Q3
983    Q4
984    Q2
985    Q4
986    Q1
987    Q4
988    Q1
989    Q3
990    Q1
991    Q4
992    Q1
993    Q4
994    Q2
995    Q3
996    Q2
997    Q1
998    Q3
999    Q4
Name: quartile, Length: 1000, dtype: category
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [76]:
results = (pd.Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index())

In [79]:
results

quartile  count       min       max
0       Q1    250 -2.949343 -0.685484
1       Q2    250 -0.683066 -0.010115
2       Q3    250 -0.010032  0.628894
3       Q4    250  0.634238  3.927528

In [81]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

### 用分类提高性能

In [82]:
N = 10000000

In [83]:
draws = pd.Series(np.random.randn(N))

In [84]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N //4))

In [85]:
categories = labels.astype('category')

In [86]:
categories

0          foo
1          bar
2          baz
3          qux
4          foo
5          bar
6          baz
7          qux
8          foo
9          bar
10         baz
11         qux
12         foo
13         bar
14         baz
15         qux
16         foo
17         bar
18         baz
19         qux
20         foo
21         bar
22         baz
23         qux
24         foo
25         bar
26         baz
27         qux
28         foo
29         bar
          ... 
9999970    baz
9999971    qux
9999972    foo
9999973    bar
9999974    baz
9999975    qux
9999976    foo
9999977    bar
9999978    baz
9999979    qux
9999980    foo
9999981    bar
9999982    baz
9999983    qux
9999984    foo
9999985    bar
9999986    baz
9999987    qux
9999988    foo
9999989    bar
9999990    baz
9999991    qux
9999992    foo
9999993    bar
9999994    baz
9999995    qux
9999996    foo
9999997    bar
9999998    baz
9999999    qux
Length: 10000000, dtype: category
Categories (4, object): [bar, baz, foo, qux]

In [87]:
draws 

0         -0.983505
1          0.930944
2         -0.811676
3         -1.830156
4         -0.138730
5          0.334088
6          0.488675
7         -0.178098
8          2.122315
9          0.061192
10         0.884111
11        -0.608506
12        -0.072052
13         0.544066
14         0.323886
15        -1.683325
16         0.526860
17         1.858791
18        -0.548419
19        -0.279397
20        -0.021299
21        -0.287990
22         0.089175
23         0.522858
24         0.572796
25        -1.760372
26         1.128179
27         1.568606
28        -0.342277
29        -0.009813
             ...   
9999970    0.261974
9999971   -0.037611
9999972   -1.360301
9999973    0.033230
9999974   -1.991496
9999975   -0.812362
9999976   -1.566573
9999977   -0.249512
9999978   -1.363836
9999979    0.317832
9999980   -0.479255
9999981   -0.891968
9999982   -0.576655
9999983   -0.008124
9999984    1.774336
9999985   -0.248741
9999986   -0.117809
9999987    0.836271
9999988    1.914641


In [88]:
labels

0          foo
1          bar
2          baz
3          qux
4          foo
5          bar
6          baz
7          qux
8          foo
9          bar
10         baz
11         qux
12         foo
13         bar
14         baz
15         qux
16         foo
17         bar
18         baz
19         qux
20         foo
21         bar
22         baz
23         qux
24         foo
25         bar
26         baz
27         qux
28         foo
29         bar
          ... 
9999970    baz
9999971    qux
9999972    foo
9999973    bar
9999974    baz
9999975    qux
9999976    foo
9999977    bar
9999978    baz
9999979    qux
9999980    foo
9999981    bar
9999982    baz
9999983    qux
9999984    foo
9999985    bar
9999986    baz
9999987    qux
9999988    foo
9999989    bar
9999990    baz
9999991    qux
9999992    foo
9999993    bar
9999994    baz
9999995    qux
9999996    foo
9999997    bar
9999998    baz
9999999    qux
Length: 10000000, dtype: object

In [89]:
categories

0          foo
1          bar
2          baz
3          qux
4          foo
5          bar
6          baz
7          qux
8          foo
9          bar
10         baz
11         qux
12         foo
13         bar
14         baz
15         qux
16         foo
17         bar
18         baz
19         qux
20         foo
21         bar
22         baz
23         qux
24         foo
25         bar
26         baz
27         qux
28         foo
29         bar
          ... 
9999970    baz
9999971    qux
9999972    foo
9999973    bar
9999974    baz
9999975    qux
9999976    foo
9999977    bar
9999978    baz
9999979    qux
9999980    foo
9999981    bar
9999982    baz
9999983    qux
9999984    foo
9999985    bar
9999986    baz
9999987    qux
9999988    foo
9999989    bar
9999990    baz
9999991    qux
9999992    foo
9999993    bar
9999994    baz
9999995    qux
9999996    foo
9999997    bar
9999998    baz
9999999    qux
Length: 10000000, dtype: category
Categories (4, object): [bar, baz, foo, qux]

In [90]:
labels.memory_usage()

80000080

In [92]:
categories.memory_usage()

10000272

In [94]:
%time _ = labels.astype('category')

Wall time: 530 ms


### 分类方法

In [95]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [96]:
s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [97]:
cat_s = s.astype('category')

In [98]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): [a, b, c, d]

In [99]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [100]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [102]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [103]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): [a, b, c, d, e]

In [104]:
cat_s2.value_counts()

d    2
c    2
b    2
a    2
e    0
dtype: int64

In [105]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [106]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): [a, b, c, d]

In [109]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): [a, b]

### 为建模创建虚拟变量

In [111]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [112]:
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1

## 12.2 GroupBy高级应用

### 分组转换和“解封”GroupBy

In [113]:
df = pd.DataFrame({'key': ['a', 'b', 'c'] * 4,
                  'value': np.arange(12.)})

In [114]:
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [115]:
g = df.groupby('key').value

In [116]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [117]:
g.transform(lambda x: x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [118]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [119]:
g.transform(lambda x: x * 2)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [121]:
g.transform(lambda x: x.rank(ascending=False))

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [122]:
def normalize(x):
    return (x - x.mean()) / x.std()

In [123]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [124]:
g.apply(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [125]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [126]:
normalized = (df['value'] - g.transform('mean')) / g.transform('std')

In [127]:
normalized

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

### 分组的时间重采样

In [128]:
N = 15 

In [131]:
times = pd.date_range('2019-05-20 00:00', freq='1min', periods=N)

In [132]:
times

DatetimeIndex(['2019-05-20 00:00:00', '2019-05-20 00:01:00',
               '2019-05-20 00:02:00', '2019-05-20 00:03:00',
               '2019-05-20 00:04:00', '2019-05-20 00:05:00',
               '2019-05-20 00:06:00', '2019-05-20 00:07:00',
               '2019-05-20 00:08:00', '2019-05-20 00:09:00',
               '2019-05-20 00:10:00', '2019-05-20 00:11:00',
               '2019-05-20 00:12:00', '2019-05-20 00:13:00',
               '2019-05-20 00:14:00'],
              dtype='datetime64[ns]', freq='T')

In [133]:
df = pd.DataFrame({'time': times, 
                  'value': np.arange(N)})

In [134]:
df

time  value
0  2019-05-20 00:00:00      0
1  2019-05-20 00:01:00      1
2  2019-05-20 00:02:00      2
3  2019-05-20 00:03:00      3
4  2019-05-20 00:04:00      4
5  2019-05-20 00:05:00      5
6  2019-05-20 00:06:00      6
7  2019-05-20 00:07:00      7
8  2019-05-20 00:08:00      8
9  2019-05-20 00:09:00      9
10 2019-05-20 00:10:00     10
11 2019-05-20 00:11:00     11
12 2019-05-20 00:12:00     12
13 2019-05-20 00:13:00     13
14 2019-05-20 00:14:00     14

In [136]:
df.set_index('time').resample('5min').count()

value
time                      
2019-05-20 00:00:00      5
2019-05-20 00:05:00      5
2019-05-20 00:10:00      5

In [137]:
df2 = pd.DataFrame({'time': times.repeat(3),
                    'key': np.tile(['a', 'b', 'c'], N),
                    'value': np.arange(N * 3.)})

In [138]:
df2

time key  value
0  2019-05-20 00:00:00   a    0.0
1  2019-05-20 00:00:00   b    1.0
2  2019-05-20 00:00:00   c    2.0
3  2019-05-20 00:01:00   a    3.0
4  2019-05-20 00:01:00   b    4.0
5  2019-05-20 00:01:00   c    5.0
6  2019-05-20 00:02:00   a    6.0
7  2019-05-20 00:02:00   b    7.0
8  2019-05-20 00:02:00   c    8.0
9  2019-05-20 00:03:00   a    9.0
10 2019-05-20 00:03:00   b   10.0
11 2019-05-20 00:03:00   c   11.0
12 2019-05-20 00:04:00   a   12.0
13 2019-05-20 00:04:00   b   13.0
14 2019-05-20 00:04:00   c   14.0
15 2019-05-20 00:05:00   a   15.0
16 2019-05-20 00:05:00   b   16.0
17 2019-05-20 00:05:00   c   17.0
18 2019-05-20 00:06:00   a   18.0
19 2019-05-20 00:06:00   b   19.0
20 2019-05-20 00:06:00   c   20.0
21 2019-05-20 00:07:00   a   21.0
22 2019-05-20 00:07:00   b   22.0
23 2019-05-20 00:07:00   c   23.0
24 2019-05-20 00:08:00   a   24.0
25 2019-05-20 00:08:00   b   25.0
26 2019-05-20 00:08:00   c   26.0
27 2019-05-20 00:09:00   a   27.0
28 2019-05-20 00:09:00   b   28.0
29 2019-05-20 00:09:00   c   29.0
30 2019-05-20 00:10:00   a   30.0
31 2019-05-20 00:10:00   b   31.0
32 2019-05-20 00:10:00   c   32.0
33 2019-05-20 00:11:00   a   33.0
34 2019-05-20 00:11:00   b   34.0
35 2019-05-20 00:11:00   c   35.0
36 2019-05-20 00:12:00   a   36.0
37 2019-05-20 00:12:00   b   37.0
38 2019-05-20 00:12:00   c   38.0
39 2019-05-20 00:13:00   a   39.0
40 2019-05-20 00:13:00   b   40.0
41 2019-05-20 00:13:00   c   41.0
42 2019-05-20 00:14:00   a   42.0
43 2019-05-20 00:14:00   b   43.0
44 2019-05-20 00:14:00   c   44.0

In [139]:
df[:7]

time  value
0 2019-05-20 00:00:00      0
1 2019-05-20 00:01:00      1
2 2019-05-20 00:02:00      2
3 2019-05-20 00:03:00      3
4 2019-05-20 00:04:00      4
5 2019-05-20 00:05:00      5
6 2019-05-20 00:06:00      6

In [165]:
time_key = pd.TimeGrouper('5min')

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: pd.TimeGrouper is deprecated and will be removed; Please use pd.Grouper(freq=...)
  """Entry point for launching an IPython kernel.


In [166]:
time_key

TimeGrouper(freq=<5 * Minutes>, axis=0, sort=True, closed='left', label='left', how='mean', convention='e', base=0)

In [171]:
resampled = (df2.set_index('time')
             .groupby(['key', time_key])
             .sum())

In [151]:
resampled

value
key time                      
a   2019-05-20 00:00:00   30.0
    2019-05-20 00:05:00  105.0
    2019-05-20 00:10:00  180.0
b   2019-05-20 00:00:00   35.0
    2019-05-20 00:05:00  110.0
    2019-05-20 00:10:00  185.0
c   2019-05-20 00:00:00   40.0
    2019-05-20 00:05:00  115.0
    2019-05-20 00:10:00  190.0

In [169]:
resampled.reset_index()

key                time  value
0   a 2019-05-20 00:00:00   30.0
1   a 2019-05-20 00:05:00  105.0
2   a 2019-05-20 00:10:00  180.0
3   b 2019-05-20 00:00:00   35.0
4   b 2019-05-20 00:05:00  110.0
5   b 2019-05-20 00:10:00  185.0
6   c 2019-05-20 00:00:00   40.0
7   c 2019-05-20 00:05:00  115.0
8   c 2019-05-20 00:10:00  190.0

## 12.3 链式编程技术

### 管道方法

## 12.4 总结

## 是时候来做做项目，实战一下了！

# 继续加油，小伙伴们！