# 第7章 数据清洗和准备

## 7.1 处理缺失数据

In [3]:
import pandas as pd
import numpy as np

In [4]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [7]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [8]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [9]:
string_data[0] = None

In [10]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [11]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### 滤除缺失数据

In [14]:
from numpy import nan as NA

In [15]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [16]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [17]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [19]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA< 6.5, 3.]])

In [20]:
data

0    1    2
0      1  6.5  3.0
1      1  NaN  NaN
2    NaN  NaN  NaN
3  False  3.0  NaN

In [21]:
cleaned = data.dropna()

In [22]:
cleaned

0    1    2
0  1  6.5  3.0

In [23]:
# 丢弃全是NA的行
cleaned = data.dropna(how='all')

In [24]:
cleaned

0    1    2
0      1  6.5  3.0
1      1  NaN  NaN
3  False  3.0  NaN

In [27]:
data[4] = NA

In [29]:
data

0    1    2   4
0      1  6.5  3.0 NaN
1      1  NaN  NaN NaN
2    NaN  NaN  NaN NaN
3  False  3.0  NaN NaN

In [30]:
# 丢弃全是NA的列
cleaned = data.dropna(how='all', axis=1)

In [31]:
cleaned

0    1    2
0      1  6.5  3.0
1      1  NaN  NaN
2    NaN  NaN  NaN
3  False  3.0  NaN

In [32]:
data

0    1    2   4
0      1  6.5  3.0 NaN
1      1  NaN  NaN NaN
2    NaN  NaN  NaN NaN
3  False  3.0  NaN NaN

In [33]:
df = pd.DataFrame(np.random.randn(7, 3))

In [34]:
df

0         1         2
0  1.764030  0.216156  1.041744
1  1.571358  0.368770  1.057556
2 -0.136411  0.159909  1.841733
3 -0.021327 -1.156274  0.651217
4  0.226195 -1.598215 -0.237642
5  0.725777 -1.282171  1.211511
6  0.333258  0.121665  1.525839

In [35]:
df.iloc[:4, 1] = NA

In [36]:
df

0         1         2
0  1.764030       NaN  1.041744
1  1.571358       NaN  1.057556
2 -0.136411       NaN  1.841733
3 -0.021327       NaN  0.651217
4  0.226195 -1.598215 -0.237642
5  0.725777 -1.282171  1.211511
6  0.333258  0.121665  1.525839

In [37]:
df.iloc[:2, 2] = NA

In [38]:
df

0         1         2
0  1.764030       NaN       NaN
1  1.571358       NaN       NaN
2 -0.136411       NaN  1.841733
3 -0.021327       NaN  0.651217
4  0.226195 -1.598215 -0.237642
5  0.725777 -1.282171  1.211511
6  0.333258  0.121665  1.525839

In [39]:
df.dropna()

0         1         2
4  0.226195 -1.598215 -0.237642
5  0.725777 -1.282171  1.211511
6  0.333258  0.121665  1.525839

In [61]:
df.dropna(thresh=2)

0         1         2
2 -0.136411       NaN  1.841733
3 -0.021327       NaN  0.651217
4  0.226195 -1.598215 -0.237642
5  0.725777 -1.282171  1.211511
6  0.333258  0.121665  1.525839

In [52]:
help(df.dropna)

Help on method dropna in module pandas.core.frame:

dropna(axis=0, how='any', thresh=None, subset=None, inplace=False) method of pandas.core.frame.DataFrame instance
    Remove missing values.
    
    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.
    
    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.
    
        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.
    
        .. deprecated:: 0.23.0: Pass tuple or list to drop on multiple
        axes.
    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.
    
        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are

In [43]:
df

0         1         2
0  1.764030       NaN       NaN
1  1.571358       NaN       NaN
2 -0.136411       NaN  1.841733
3 -0.021327       NaN  0.651217
4  0.226195 -1.598215 -0.237642
5  0.725777 -1.282171  1.211511
6  0.333258  0.121665  1.525839

### 填充缺失数据

In [62]:
df.fillna(0)

0         1         2
0  1.764030  0.000000  0.000000
1  1.571358  0.000000  0.000000
2 -0.136411  0.000000  1.841733
3 -0.021327  0.000000  0.651217
4  0.226195 -1.598215 -0.237642
5  0.725777 -1.282171  1.211511
6  0.333258  0.121665  1.525839

In [64]:
# 对列进行填充
df.fillna({1:0.5, 2:0})

0         1         2
0  1.764030  0.500000  0.000000
1  1.571358  0.500000  0.000000
2 -0.136411  0.500000  1.841733
3 -0.021327  0.500000  0.651217
4  0.226195 -1.598215 -0.237642
5  0.725777 -1.282171  1.211511
6  0.333258  0.121665  1.525839

In [65]:
_ = df.fillna(0, inplace=True)

In [66]:
df

0         1         2
0  1.764030  0.000000  0.000000
1  1.571358  0.000000  0.000000
2 -0.136411  0.000000  1.841733
3 -0.021327  0.000000  0.651217
4  0.226195 -1.598215 -0.237642
5  0.725777 -1.282171  1.211511
6  0.333258  0.121665  1.525839

In [70]:
df = pd.DataFrame(np.random.randn(6,3))

In [72]:
df.iloc[2:, 1] = NA

In [73]:
df

0         1         2
0 -1.124432 -0.289993 -0.542288
1 -1.619708  0.899245 -1.249297
2  1.203298       NaN  0.827352
3  0.639155       NaN -0.425178
4 -1.849638       NaN  0.888146
5 -1.499204       NaN  1.307610

In [74]:
df.iloc[4:, 2] = NA

In [75]:
df

0         1         2
0 -1.124432 -0.289993 -0.542288
1 -1.619708  0.899245 -1.249297
2  1.203298       NaN  0.827352
3  0.639155       NaN -0.425178
4 -1.849638       NaN       NaN
5 -1.499204       NaN       NaN

In [76]:
df.fillna(method='ffill')

0         1         2
0 -1.124432 -0.289993 -0.542288
1 -1.619708  0.899245 -1.249297
2  1.203298  0.899245  0.827352
3  0.639155  0.899245 -0.425178
4 -1.849638  0.899245 -0.425178
5 -1.499204  0.899245 -0.425178

In [77]:
df

0         1         2
0 -1.124432 -0.289993 -0.542288
1 -1.619708  0.899245 -1.249297
2  1.203298       NaN  0.827352
3  0.639155       NaN -0.425178
4 -1.849638       NaN       NaN
5 -1.499204       NaN       NaN

In [78]:
df.fillna(method='ffill', limit=2)

0         1         2
0 -1.124432 -0.289993 -0.542288
1 -1.619708  0.899245 -1.249297
2  1.203298  0.899245  0.827352
3  0.639155  0.899245 -0.425178
4 -1.849638       NaN -0.425178
5 -1.499204       NaN -0.425178

In [79]:
data = pd.Series([1., NA, 305, NA, 7])

In [80]:
data.fillna(data.mean())

0      1.000000
1    104.333333
2    305.000000
3    104.333333
4      7.000000
dtype: float64

## 7.2 数据转换

### 移除重复数据

In [84]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                            'k2':[1, 1, 2, 3, 3, 4, 4]})

In [85]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [86]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [87]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [88]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [89]:
data['v1'] = range(7)

In [92]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [90]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [93]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [91]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

#### 利用函数或映射进行数据转换

In [104]:
data = pd.DataFrame({'food':['bacon', 'pulled pork', 'bacon',
                            'Pastrami', 'corned beef','Bacon', 
                            'pastrami', 'honey ham', 'nova lox'],
                    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [105]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [106]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

In [107]:
lowercased = data['food'].str.lower()

In [108]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [109]:
data['animal'] = lowercased.map(meat_to_animal)

In [110]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [111]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### 替换值

In [112]:
data = pd.Series([1., -999., 2., -999, -1000., 3.])

In [113]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [114]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [115]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [116]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [117]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [118]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### 重命名轴索引

In [127]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [128]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [129]:
transform = lambda x: x[:4].upper()

In [122]:
transform

<function __main__.<lambda>(x)>

In [130]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [131]:
data.index = data.index.map(transform)

In [132]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [133]:
data.rename(index={'OHIO': 'INDIANA'},
           columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [134]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [135]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### 离散化和面元划分

In [136]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
 index=['Ohio', 'Colorado', 'New York'],
....: columns=['one', 'two', 'three', 'four'])

In [137]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [139]:
bins = [18, 25, 35, 60, 100]

In [140]:
cats = pd.cut(ages, bins)

In [141]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [142]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [144]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [145]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [146]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [147]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [148]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [150]:
data = np.random.rand(20)

In [151]:
data

array([0.0677154 , 0.70490977, 0.76174782, 0.33827441, 0.99897307,
       0.83151924, 0.06270773, 0.78315842, 0.31740413, 0.37959451,
       0.11088554, 0.81460589, 0.50902303, 0.889477  , 0.6035941 ,
       0.27730021, 0.33558281, 0.72108296, 0.77882311, 0.24489505])

In [152]:
pd.cut(data, 4, precision=2)

[(0.062, 0.3], (0.53, 0.76], (0.53, 0.76], (0.3, 0.53], (0.76, 1.0], ..., (0.062, 0.3], (0.3, 0.53], (0.53, 0.76], (0.76, 1.0], (0.062, 0.3]]
Length: 20
Categories (4, interval[float64]): [(0.062, 0.3] < (0.3, 0.53] < (0.53, 0.76] < (0.76, 1.0]]

In [153]:
data = np.random.randn(1000)

In [154]:
data

array([-2.11554086e-01,  7.35604017e-01, -4.04142030e-01,  5.66803424e-01,
        1.53212124e+00,  6.40077508e-02, -6.91385551e-01,  5.99803897e-01,
        2.01256590e+00, -1.11320866e+00,  1.70171376e+00, -2.09398798e-01,
        5.48027209e-01, -5.82723374e-01, -2.33773996e-01, -2.90900154e-01,
        3.90054422e-01, -1.08405224e+00,  1.89691805e+00,  7.23713815e-01,
       -1.82107560e+00, -1.03538202e+00,  1.26988628e+00, -1.03662095e+00,
        7.24248302e-01,  1.70115229e+00,  1.34253707e-01, -7.68302252e-01,
       -1.21553958e+00,  1.99148862e-01,  2.30154284e-02, -1.28940656e+00,
       -8.11738567e-01,  1.06894045e+00, -9.19720651e-01,  1.69610054e+00,
        1.50771336e+00, -5.92459277e-01, -1.80095750e+00, -1.50526080e+00,
        1.69754341e+00, -5.97567998e-01, -7.84439288e-01,  7.90019516e-01,
        9.49731837e-01, -1.71450676e+00, -1.19241600e+00,  6.03283387e-01,
        1.07138548e+00,  8.32509840e-01, -5.13007186e-01, -1.17122574e-01,
        1.60082607e+00,  

In [155]:
cats = pd.qcut(data, 4)

In [156]:
cats

[(-0.66, 0.0171], (0.724, 3.507], (-0.66, 0.0171], (0.0171, 0.724], (0.724, 3.507], ..., (0.0171, 0.724], (-3.247, -0.66], (-3.247, -0.66], (0.724, 3.507], (0.0171, 0.724]]
Length: 1000
Categories (4, interval[float64]): [(-3.247, -0.66] < (-0.66, 0.0171] < (0.0171, 0.724] < (0.724, 3.507]]

In [157]:
pd.value_counts(cats)

(0.724, 3.507]     250
(0.0171, 0.724]    250
(-0.66, 0.0171]    250
(-3.247, -0.66]    250
dtype: int64

### 检测和过滤异常值

In [163]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [159]:
data

0         1         2         3
0   -1.589501  0.595465 -2.154831 -0.651009
1   -0.029532 -0.153586  0.071970 -0.266067
2    1.750106 -0.494059 -0.498686 -0.863608
3   -0.857521 -0.175157 -2.423430  0.995164
4   -0.292350  1.073614 -0.145632 -0.675640
5    0.046540 -0.974704 -0.699502 -0.363872
6   -0.605147  1.069288  0.229481  0.694380
7   -0.282361 -1.016353 -0.327770  1.314095
8    0.697649 -0.797280 -0.918182  0.683819
9    0.126161 -1.252406  1.027702 -0.053128
10   3.672287 -1.159072 -0.169229  0.083090
11   0.305146 -1.216271 -1.286794 -0.345120
12   1.390682 -0.843228 -0.850123  0.715015
13   1.348799 -0.581019 -0.992833 -0.238412
14   0.376334  1.791235 -1.907150 -0.341140
15  -0.079789  1.026930  0.073708  1.028223
16  -1.463518 -0.540593  0.016300  0.739402
17  -1.946307 -0.788737 -1.701154  0.158363
18  -0.083811 -1.554697  1.054109 -0.450993
19  -0.626535 -1.119102 -0.488960  0.946857
20   0.964380  0.816457  0.734872 -0.078564
21  -0.039210  1.579608 -0.715764  1.145938
22  -0.811294  0.823511 -0.622919  0.323995
23  -1.422282  1.853181 -0.451071  1.228515
24  -0.850028 -1.411067 -0.596041  2.889331
25   1.513621 -1.164591  1.075270  0.791216
26   0.085539  1.341865  1.302895  0.031804
27   0.530652 -1.002124 -1.464450  0.047470
28   0.657377  1.142685 -0.530164 -0.682927
29  -0.096079  0.974972 -1.060822  1.099151
..        ...       ...       ...       ...
970  1.621546 -1.048290 -2.182511 -1.105147
971 -0.034663  1.660956  0.097603 -0.454145
972  1.102340 -1.582591  0.518312 -0.028049
973 -1.826470 -0.105653  1.311717  0.295828
974  1.027823 -0.232333 -0.732717  0.075437
975  0.605160  0.094622  1.148494  0.526403
976  0.093982 -1.288268  0.858031  1.470185
977 -1.261222  1.750385 -1.491346  0.576767
978 -0.037028 -0.347801 -1.536489 -0.128197
979  0.854277 -0.920396 -1.656566  1.177051
980  0.143549 -1.100049  2.243576  0.515621
981 -0.530264 -1.208016  0.936168  0.300788
982  0.760441 -0.371813 -0.406517  0.196687
983  0.752822 -0.157958  0.217771  1.422688
984 -0.656360 -1.204601 -0.197662  0.060449
985 -0.726107  0.764860 -0.625867 -0.711295
986  0.802362 -1.149997 -0.578699 -1.201849
987  0.491363 -0.040353 -1.175105 -0.817155
988 -0.145143  0.610099 -0.808814 -1.503048
989  0.695312  1.442286 -0.019685 -2.612303
990 -0.242951  0.833363  1.453269 -0.152080
991 -1.527412  0.582973 -0.581742  0.403459
992 -0.265283  0.429448  1.364162  0.279020
993  0.764733  0.199795 -0.567936 -0.723595
994  2.427548  1.625878  0.592178 -1.475248
995 -0.257341 -0.769555 -0.329874  1.398403
996 -1.190662 -0.401329  0.206105 -0.001965
997  2.584320  2.490348 -0.448610  1.380703
998  0.567143  0.444260 -0.129520 -0.110935
999  0.270376 -0.688519 -0.337770  0.817794

[1000 rows x 4 columns]

In [164]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.002635     0.015660    -0.047244    -0.022352
std       0.984903     0.968730     1.019109     1.000485
min      -3.483052    -3.218293    -3.365888    -3.316437
25%      -0.640403    -0.649050    -0.731137    -0.759923
50%       0.010251     0.005030    -0.038623    -0.027857
75%       0.634522     0.687352     0.612745     0.686394
max       2.676594     2.881796     3.113215     2.915121

In [165]:
col = data[2]

In [166]:
col[np.abs(col) > 3]

238    3.113215
691   -3.365888
Name: 2, dtype: float64

In [167]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
238 -1.603155 -0.326606  3.113215  1.379113
323  1.117185 -3.066894  1.673273  0.907542
404 -3.483052 -1.818079 -0.611631 -1.336208
457 -3.077224 -1.679464 -2.809096 -0.698782
691 -0.680978 -1.129441 -3.365888  1.506093
733 -0.815199 -0.477479  0.586776 -3.316437
794 -1.420184 -3.218293 -0.592097  0.411905
924 -3.252598  1.355657 -0.394149  0.843455

In [168]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [169]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.003448     0.015946    -0.046992    -0.022035
std       0.982264     0.967813     1.017636     0.999492
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.640403    -0.649050    -0.731137    -0.759923
50%       0.010251     0.005030    -0.038623    -0.027857
75%       0.634522     0.687352     0.612745     0.686394
max       2.676594     2.881796     3.000000     2.915121

In [170]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0  1.0 -1.0
1 -1.0  1.0 -1.0  1.0
2  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0 -1.0

### 排列和随机采样

In [171]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [172]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [173]:
sampler = np.random.permutation(5)

In [174]:
sampler

array([3, 4, 1, 0, 2])

In [175]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [176]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
4  16  17  18  19
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11

In [177]:
df.sample(n=3)

0   1   2   3
1   4   5   6   7
4  16  17  18  19
3  12  13  14  15

In [178]:
choices = pd.Series([5, 7, -1, 6, 4])

In [179]:
draws = choices.sample(n=10, replace=True)

In [180]:
draws

4    4
4    4
3    6
4    4
0    5
3    6
0    5
0    5
0    5
3    6
dtype: int64

### 计算指标/哑变量

In [185]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                 'data1': range(6)})

In [186]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [188]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [189]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [190]:
df_with_dumjy = df[['data1']].join(dummies)

In [191]:
df_with_dumjy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [192]:
mnames = ['movie_id', 'title', 'genres']

In [196]:
movies = pd.read_table('.\movies.dat',sep='::',
                      header=None, names=mnames, engine='python')

In [197]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [198]:
all_genres = []

In [200]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [201]:
all_genres

['Animation',
 "Children's",
 'Comedy',
 'Adventure',
 "Children's",
 'Fantasy',
 'Comedy',
 'Romance',
 'Comedy',
 'Drama',
 'Comedy',
 'Action',
 'Crime',
 'Thriller',
 'Comedy',
 'Romance',
 'Adventure',
 "Children's",
 'Action',
 'Action',
 'Adventure',
 'Thriller',
 'Comedy',
 'Drama',
 'Romance',
 'Comedy',
 'Horror',
 'Animation',
 "Children's",
 'Drama',
 'Action',
 'Adventure',
 'Romance',
 'Drama',
 'Thriller',
 'Drama',
 'Romance',
 'Thriller',
 'Comedy',
 'Action',
 'Action',
 'Comedy',
 'Drama',
 'Crime',
 'Drama',
 'Thriller',
 'Thriller',
 'Drama',
 'Sci-Fi',
 'Drama',
 'Romance',
 'Drama',
 'Drama',
 'Romance',
 'Adventure',
 'Sci-Fi',
 'Drama',
 'Drama',
 'Drama',
 'Sci-Fi',
 'Adventure',
 'Romance',
 "Children's",
 'Comedy',
 'Drama',
 'Drama',
 'Romance',
 'Drama',
 'Documentary',
 'Comedy',
 'Comedy',
 'Romance',
 'Drama',
 'Drama',
 'War',
 'Action',
 'Crime',
 'Drama',
 'Drama',
 'Action',
 'Adventure',
 'Comedy',
 'Drama',
 'Drama',
 'Romance',
 'Crime',
 'Thrill

In [202]:
genres = pd.unique(all_genres)

In [203]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [204]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [205]:
zero_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [206]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [207]:
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
1           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
2           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
4           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
5           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
6           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
7           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
8           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
9           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
10          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
11          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
12          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
13          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
14          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
15          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
16          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
17          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
18          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
19          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
20          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
21          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
22          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
23          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
24          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
25          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
26          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
27          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
28          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
29          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3853        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3854        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3855        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3856        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3857        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3858        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3859        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3860        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3861        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3862        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3863        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3864        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3865        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3866        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3867        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3868        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3869        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3870        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3871        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3872        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3873        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3874        0.0         0.0    

In [208]:
gen = movies.genres[0]

In [209]:
gen

"Animation|Children's|Comedy"

In [210]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [211]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [213]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [214]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [215]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [216]:
np.random.seed(12345)

In [217]:
values = np.random.rand(10)

In [218]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [224]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [225]:
bins

[0, 0.2, 0.4, 0.6, 0.8, 1]

In [226]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## 7.3字符串操作

### 字符串对象方法

In [227]:
val = 'a,b, guido'

In [228]:
val.split(',')

['a', 'b', ' guido']

In [229]:
pieces = [x.strip() for x in val.split(',')]

In [230]:
pieces

['a', 'b', 'guido']

In [231]:
first, second ,third = pieces

first

In [233]:
first + '::' + second + '::' + third

'a::b::guido'

In [234]:
'::'.join(pieces)

'a::b::guido'

In [235]:
'guido' in val

True

In [236]:
val.index(',')

1

In [237]:
val.find(':')

-1

In [238]:
val.index(':')

ValueError: substring not found

In [239]:
val

'a,b, guido'

In [240]:
val.count(',')

2

In [241]:
val.replace(',', '')

'ab guido'

### 正则表达式

In [242]:
import re

In [243]:
text = "foo    bar\t baz \tqux"

In [244]:
text

'foo    bar\t baz \tqux'

In [245]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [246]:
regex = re.compile('\s+')

In [247]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [248]:
regex.findall(text)

['    ', '\t ', ' \t']

In [249]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

In [250]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [251]:
# re.IGNORECASE makes the regex case-insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

In [252]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [253]:
m = regex.search(text)

In [254]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [255]:
m.group()

'dave@google.com'

In [256]:
text[m.start():m.end()]

'dave@google.com'

In [257]:
print(regex.match(text))

None


In [258]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [259]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [260]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [261]:
m = regex.match('wesm@bright.net')

In [262]:
m.groups()

('wesm', 'bright', 'net')

In [263]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [264]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



In [265]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [266]:
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Wes': nan}

In [267]:
data = pd.Series(data)

In [268]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [269]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [270]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [271]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [272]:
data.str.findall(pattern, flags = re.I)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [273]:
matches = data.str.match(pattern, flags=re.I)

In [275]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [276]:
matches.str.get(1)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [277]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [278]:
matches.str[0]

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [279]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

## 7.4 总结

高效的数据准备，可以使得我们有更多的精力用于数据分析。

# 继续加油！