In [ ]:
基于NumPy的算法要比纯Python快10-100倍不等（甚至更快），例子如下，而且使用的内存更少！

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10):my_arr2 = my_arr * 2

Wall time: 49 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.33 s


In [ ]:
NumPy的ndarry：一种多维数组对象

In [7]:
import numpy as np

In [11]:
# Generate some randome data

In [12]:
data = np.random.randn(2,3)

In [13]:
data

array([[-1.36631677, -1.18468359,  0.44777336],
       [-0.9973282 ,  1.10226268,  0.40077455]])

In [14]:
data * 10

array([[-13.66316765, -11.8468359 ,   4.47773364],
       [ -9.97328203,  11.02262678,   4.00774551]])

In [15]:
data + data

array([[-2.73263353, -2.36936718,  0.89554673],
       [-1.99465641,  2.20452536,  0.8015491 ]])

In [ ]:
使用NumPy惯用法import numpy as np
ndarray是一个通用的同构数据多维容器，其中的所有元素必须是相同的类型。
每个数组都有一个shape（一个表示各维度大小的元组）和一个dtype
(一个用于说明数组数据类型的对象)

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')